import type { Metadata } from "next";
import { LegalDoc, LegalSection } from "@/components/LegalDoc";

export const metadata: Metadata = {
  title: "Privacy Policy — Digital Sentinel",
  description: "What Digital Sentinel collects, how it's used, and how your vault data is protected.",
  alternates: { canonical: "/privacy" },
  robots: { index: false },
};

export default function PrivacyPage() {
  return (
    <LegalDoc title="Privacy Policy" lastUpdated="July 30, 2026">
      <LegalSection title="1. What we collect">
        <p>We collect information you provide directly and information generated by using the Service:</p>
        <ul className="ml-5 list-disc space-y-2">
          <li>Account information: name, email, password (stored hashed, never in plain text).</li>
          <li>
            Vault contents: photos, notes, and codes you choose to save — encrypted on your
            device before it reaches our servers.
          </li>
          <li>Trusted contact details you add: name, relationship, and permission level.</li>
          <li>
            Dispatch and membership activity: covered-event usage, dispatch requests, and support
            messages.
          </li>
          <li>Billing information, processed by a PCI-compliant third-party payment processor — we don&rsquo;t store full card numbers.</li>
          <li>Standard technical data: device type, app version, and basic usage analytics.</li>
        </ul>
      </LegalSection>

      <LegalSection title="2. How we use it">
        <ul className="ml-5 list-disc space-y-2">
          <li>To provide the Service — dispatching techs, maintaining your vault, and processing billing.</li>
          <li>To communicate with you about your membership, dispatch requests, and support inquiries.</li>
          <li>To improve reliability and safety, including investigating reported incidents.</li>
          <li>To meet legal and regulatory obligations.</li>
        </ul>
        <p>We do not sell your personal information.</p>
      </LegalSection>

      <LegalSection title="3. Who we share it with">
        <p>We share limited information only where necessary to operate the Service:</p>
        <ul className="ml-5 list-disc space-y-2">
          <li>
            With the Tech assigned to your dispatch request — your name, general location, and
            the nature of the request, not your vault contents.
          </li>
          <li>With our payment processor, to bill your membership.</li>
          <li>With infrastructure providers (hosting, database, email delivery) under standard confidentiality terms.</li>
          <li>When required by law, or to protect the safety of members or the public.</li>
        </ul>
      </LegalSection>

      <LegalSection title="4. How your vault is protected">
        <p>
          Vault entries are encrypted on your device before syncing. Access to your vault is
          restricted to your account and anyone you explicitly grant access to via trusted
          contacts. Dispatch Techs do not have standing access to your vault.
        </p>
      </LegalSection>

      <LegalSection title="5. Cookies">
        <p>
          We use essential cookies required for the site and app to function (like keeping you
          signed in), and may use limited analytics cookies to understand product usage. See our{" "}
          <a href="/cookies" className="text-brass hover:underline">
            Cookie Preferences
          </a>{" "}
          page for details and controls.
        </p>
      </LegalSection>

      <LegalSection title="6. Your rights">
        <p>
          Depending on where you live, you may have rights to access, correct, delete, or export
          your personal information, and to object to certain processing. Contact us to exercise
          any of these rights — we&rsquo;ll respond within a reasonable time and in line with
          applicable law.
        </p>
      </LegalSection>

      <LegalSection title="7. Data retention">
        <p>
          We retain account and vault data for as long as your membership is active, and for a
          limited period after cancellation as needed for legal, billing, or dispute-resolution
          purposes. You can request earlier deletion by contacting support.
        </p>
      </LegalSection>

      <LegalSection title="8. Changes to this policy">
        <p>
          We may update this Privacy Policy from time to time. Material changes will be
          communicated through the app or by email before they take effect.
        </p>
      </LegalSection>

      <LegalSection title="9. Contact">
        <p>
          Privacy questions or requests can be sent to{" "}
          <a href="mailto:support@digitalsentinel.com" className="text-brass hover:underline">
            support@digitalsentinel.com
          </a>{" "}
          or through our{" "}
          <a href="/contact" className="text-brass hover:underline">
            contact page
          </a>
          .
        </p>
      </LegalSection>
    </LegalDoc>
  );
}
